[2025-06-03T20:31:49.029+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [queued]>
[2025-06-03T20:31:49.039+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [queued]>
[2025-06-03T20:31:49.040+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 7
[2025-06-03T20:31:49.054+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-05-31 00:00:00+00:00
[2025-06-03T20:31:49.060+0000] {standard_task_runner.py:60} INFO - Started process 64848 to run task
[2025-06-03T20:31:49.064+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'delete_data_from_table', 'scheduled__2025-05-31T00:00:00+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_dag.py', '--cfg-path', '/tmp/tmpui60248_']
[2025-06-03T20:31:49.066+0000] {standard_task_runner.py:88} INFO - Job 379: Subtask delete_data_from_table
[2025-06-03T20:31:49.141+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [running]> on host 4bea2aab752f
[2025-06-03T20:31:49.225+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-31T00:00:00+00:00'
[2025-06-03T20:31:49.227+0000] {sql.py:276} INFO - Executing: 
            delete from dag_runs where dt = '2025-05-31' and dag_id = 'dag_with_postgres_operator_v01';
        
[2025-06-03T20:31:49.237+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T20:31:49.249+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T20:31:49.287+0000] {sql.py:450} INFO - Running statement: 
            delete from dag_runs where dt = '2025-05-31' and dag_id = 'dag_with_postgres_operator_v01';
        , parameters: None
[2025-06-03T20:31:49.296+0000] {sql.py:459} INFO - Rows affected: 1
[2025-06-03T20:31:49.330+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=delete_data_from_table, execution_date=20250531T000000, start_date=20250603T203149, end_date=20250603T203149
[2025-06-03T20:31:49.358+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-03T20:31:49.384+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
