[2025-06-03T20:29:46.737+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [queued]>
[2025-06-03T20:29:46.759+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [queued]>
[2025-06-03T20:29:46.760+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2025-06-03T20:29:46.781+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-05-31 00:00:00+00:00
[2025-06-03T20:29:46.793+0000] {standard_task_runner.py:60} INFO - Started process 62904 to run task
[2025-06-03T20:29:46.800+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'delete_data_from_table', 'scheduled__2025-05-31T00:00:00+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_dag.py', '--cfg-path', '/tmp/tmpsdc2e6ig']
[2025-06-03T20:29:46.802+0000] {standard_task_runner.py:88} INFO - Job 371: Subtask delete_data_from_table
[2025-06-03T20:29:46.912+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [running]> on host 4bea2aab752f
[2025-06-03T20:29:47.013+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-31T00:00:00+00:00'
[2025-06-03T20:29:47.017+0000] {sql.py:276} INFO - Executing: 
            delete from dag_runs where dt = '2025-05-31' and dag_id = 'dag_with_postgres_operator_v01';
        
[2025-06-03T20:29:47.033+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T20:29:47.054+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T20:29:47.095+0000] {sql.py:450} INFO - Running statement: 
            delete from dag_runs where dt = '2025-05-31' and dag_id = 'dag_with_postgres_operator_v01';
        , parameters: None
[2025-06-03T20:29:47.103+0000] {sql.py:459} INFO - Rows affected: 0
[2025-06-03T20:29:47.129+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=delete_data_from_table, execution_date=20250531T000000, start_date=20250603T202946, end_date=20250603T202947
[2025-06-03T20:29:47.173+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-03T20:29:47.208+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-05T16:04:16.960+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [queued]>
[2025-06-05T16:04:16.990+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [queued]>
[2025-06-05T16:04:16.991+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2025-06-05T16:04:17.022+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-05-31 00:00:00+00:00
[2025-06-05T16:04:17.033+0000] {standard_task_runner.py:60} INFO - Started process 51075 to run task
[2025-06-05T16:04:17.043+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'delete_data_from_table', 'scheduled__2025-05-31T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_dag.py', '--cfg-path', '/tmp/tmp0vtuzm2v']
[2025-06-05T16:04:17.053+0000] {standard_task_runner.py:88} INFO - Job 81: Subtask delete_data_from_table
[2025-06-05T16:04:17.320+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.delete_data_from_table scheduled__2025-05-31T00:00:00+00:00 [running]> on host 14aa2e8b0b7d
[2025-06-05T16:04:17.490+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-31T00:00:00+00:00'
[2025-06-05T16:04:17.493+0000] {sql.py:276} INFO - Executing: 
            delete from dag_runs where dt = '2025-05-31' and dag_id = 'dag_with_postgres_operator_v01';
        
[2025-06-05T16:04:17.521+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-05T16:04:17.552+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-05T16:04:17.595+0000] {sql.py:450} INFO - Running statement: 
            delete from dag_runs where dt = '2025-05-31' and dag_id = 'dag_with_postgres_operator_v01';
        , parameters: None
[2025-06-05T16:04:17.605+0000] {sql.py:459} INFO - Rows affected: 0
[2025-06-05T16:04:17.629+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=delete_data_from_table, execution_date=20250531T000000, start_date=20250605T160416, end_date=20250605T160417
[2025-06-05T16:04:17.685+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-05T16:04:17.762+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
